# Generated by Django 5.0.1 on 2024-01-19 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0006_groupstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='opponent_goals_1st_leg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='opponent goals 1st leg'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='player_goals_1st_leg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='player goals 1st leg'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='draws',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='draws'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='goals_against',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='goals against'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='goals_for',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='goals for'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='loses',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='loses'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='matches_played',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='matches played'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='wins',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='wins'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of players'),
        ),
    ]
