# Generated by Django 5.0.1 on 2024-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0008_registrationstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'verbose_name_plural': 'Registration Status'},
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='status',
            field=models.BooleanField(unique=True, verbose_name='status'),
        ),
    ]
