# Generated by Django 5.0.1 on 2024-01-23 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0010_alter_registrationstatus_status_knockoutstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='added_to_teams_chat',
            field=models.BooleanField(default=False, verbose_name='added to Teams chat'),
        ),
        migrations.AddField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
    ]
