# Generated by Django 5.0.1 on 2024-01-25 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0011_player_added_to_teams_chat_player_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_group', to='tournament_bracket_generator.groupstage', verbose_name='group_name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='registration date'),
        ),
    ]
