# Generated by Django 5.0.1 on 2024-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0012_fixture_group_alter_player_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], max_length=1, null=True, verbose_name='group_name'),
        ),
    ]
