# Generated by Django 5.0.1 on 2024-01-29 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0014_remove_groupstage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='match number'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='opponent_goals_2nd_leg',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='opponent goals 2nd leg'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='player_goals_2nd_leg',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='player goals 2nd leg'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], max_length=1, null=True, verbose_name='group name'),
        ),
    ]
