# Generated by Django 5.0.1 on 2024-01-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket_generator', '0015_fixture_match_number_fixture_opponent_goals_2nd_leg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knockoutstage',
            name='opponent_name',
        ),
        migrations.RemoveField(
            model_name='knockoutstage',
            name='player_name',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='KnockoutStage',
        ),
    ]
